# Generated by Django 6.1.1 on 2026-09-27 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BioParagraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Paragraph content for About Me section')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Bio Paragraph',
                'verbose_name_plural': 'Bio Paragraphs',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('other', 'Other')], default='email', max_length=20)),
                ('label', models.CharField(blank=True, help_text='e.g. Personal Email, Work Email, Mobile', max_length=100)),
                ('value', models.CharField(max_length=255)),
                ('link_url', models.CharField(help_text='e.g. mailto:khatriharimohan@gmail.com or tel:+9779866108477', max_length=255)),
                ('lucide_icon', models.CharField(default='mail', help_text='Lucide icon name e.g. mail, phone', max_length=50)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Contact Info',
                'verbose_name_plural': 'Contact Info Items',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Harimohan Khatri', max_length=100)),
                ('role', models.CharField(default='Educator and Researcher', help_text='e.g., Educator and Researcher', max_length=100)),
                ('focus_area', models.CharField(default='Learning Models and Visual Computing', help_text='e.g., Learning Models and Visual Computing', max_length=200)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('email', models.EmailField(default='khatriharimohan@gmail.com', max_length=254)),
                ('work_email', models.EmailField(blank=True, default='harimohank@nec.edu.np', max_length=254, null=True)),
                ('phone', models.CharField(blank=True, default='+977 9866108477', max_length=50, null=True)),
                ('cv_file', models.FileField(blank=True, null=True, upload_to='cv/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(help_text='Detailed info text shown when toggling Info')),
                ('status', models.CharField(choices=[('idea', 'Idea'), ('working', 'Working'), ('published', 'Published')], default='working', max_length=20)),
                ('collaborate_email', models.EmailField(blank=True, help_text='Email for collaborate button if applicable', max_length=254, null=True)),
                ('project_url', models.URLField(blank=True, null=True)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(help_text='Detailed info text shown when toggling Info')),
                ('status', models.CharField(choices=[('idea', 'Idea'), ('working', 'Working'), ('published', 'Published')], default='working', max_length=20)),
                ('publication_url', models.URLField(blank=True, help_text='Optional link to publication', null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Research',
                'verbose_name_plural': 'Research Items',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(help_text='e.g. LinkedIn, Google Scholar, GitHub, ORCID', max_length=100)),
                ('url', models.URLField()),
                ('icon', models.FileField(blank=True, help_text='SVG icon file', null=True, upload_to='social_icons/')),
                ('icon_static_name', models.CharField(blank=True, help_text='Fallback static SVG filename like linkedin.svg', max_length=100)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Teaching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200)),
                ('is_active_semester', models.BooleanField(default=False, help_text='Active this semester (shows glow dot and classroom link)')),
                ('materials_url', models.URLField(blank=True, help_text='Link to Course Materials', null=True)),
                ('classroom_url', models.URLField(blank=True, help_text='Link to Google Classroom', null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Teaching Course',
                'verbose_name_plural': 'Teaching Courses',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='ProjectTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='main.project')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='ResearchTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='main.research')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
    ]
